language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  - MAPSERVER_COMMIT=rel-6-2-1  # v6.2.1
  - MAPSERVER_COMMIT=           # repository HEAD
before_install:
  - sudo apt-get install libgif-dev                   # mapserver dependencies
  - sh ./tools/install-deps.sh /tmp $MAPSERVER_COMMIT # install the dependencies
  - export PATH=/tmp/mapserver-install/bin:${PATH} # ensure `node-gyp` can find `mapserver-config`